services:
  - type: web
    name: wisedeep-backend
    env: node
    buildCommand: npm install --legacy-peer-deps
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
